version: '3.4'
services:

  node_app:
    build:
      context: ../
      dockerfile: ./docker/DockerfileNode
    container_name: node_app
    ports:
      - 8080:8080 # node app
      - 9229:9229 # debugger
    env_file:
      - ../.env
    volumes:
      - ./bash_history.log:/root/.bash_history #container bash history will remain persist
      - ../:/app
      - /app/node_modules # don't mount anything at this path
    links:
      - mongodb
      - mysqldb
    # command: npm run debug6
    # command: sh -c "ls -la ./node_modules"
    command: sh -c "export NODE_ENV=development && nodemon --inspect=0.0.0.0 server.js"
    # command: sh -c "cross-env NODE_ENV=development node --inspect=0.0.0.0 --inspect-brk server.js"
    # command: sh -c "cross-env NODE_ENV=development node --inspect=0.0.0.0 --inspect-brk server.js"
    # command: sh -c "cross-env NODE_ENV=test babel-tape-runner src/tests/test-*.js"

  mongodb:
    image: mongo:3.6
    container_name: mongodb
    command: mongod --noprealloc
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db

  mysqldb:
    build:
      context: ../
      dockerfile: ./docker/DockerfileMysql
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql

