version: '3.4'
services:

  express_app:
    build:
      context: ../
      dockerfile: ./docker/DockerfileNode
    image: express_app_image # 
    container_name: express_app
    ports:
      - 8080:8080 # express app
      - 9229:9229 # vscode debugger
    env_file:
      - ../.env
    volumes:
      - ./bash_history.log:/root/.bash_history #container bash history will remain persist
      - ../:/app
      - /app/node_modules # don't mount anything at this path
    links:
      - mongodb
      - postgresdb
    command: sh -c "npm run dev" # use this for development
    # command: sh -c "npm run pretest"
    # command: sh -c "npm run test"
    # command: sh -c "export NODE_ENV=development && nodemon --inspect=0.0.0.0 --ignore node_modules/ server.js"
    networks:
      - frontend

  mongodb:
    image: mongo:3.6
    container_name: mongodb
    command: mongod --noprealloc
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
    networks:
      - frontend

  postgresdb:
    image: postgres:13-alpine
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - frontend

networks:
  frontend: