swagger: "2.0"

info:
  title: API Specification
  description: API Specification
  version: 1.0.0
  contact:
    email: "saifkhan912@gmail.com"

paths:
  /api/survey:
    post:
      summary: Collect a survey
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - survey
      parameters:
        - in: formData
          name: name
          type: string
          description: Your Name
        - in: formData
          name: position
          type: string
          description: Position/Title for example Senior Software Engineer
          default: Software Engineer
        - in: formData
          name: feedback
          type: string
          enum: [Very satisfied, Somewhat satisfied,Neutral,Very dissatisfied]
          description: How would you describe your overall level of job satisfaction?
          required: true

      responses:
        200:
          description: |
            {"message": "Your survey has been received. Thank you."}
        400:
          description: |
            {"errors":{"name":["required field"]}}

    get:
      summary: Get surveys List
      description: Get surveys List
      tags:
        - survey
      responses:
        200:
          description: |
            [List of surveys]

  /api/contactus:
    post:
      summary: Submit contact us message
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - contactus
      parameters:
        - in: formData
          name: name
          type: string
          description: Your Name
        - in: formData
          name: email
          type: string
          description: Email
        - in: formData
          name: message
          type: string
          description: message
          required: true
      responses:
        200:
          description: |
            {"message": "Your message has been received. Thank you."}
        400:
          description: |
            {"errors":{"name":["required field"]}}

    get:
      summary: contact us
      description: contact us
      tags:
        - contactus
      responses:
        200:
          description: Success

